name: book_home_library_server
description: An empty conduit application.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  conduit: ^3.0.0
  sqflite_common: ^2.2.1+1
  sqflite_common_ffi: ^2.1.1
  enum_object: ^0.0.2

dev_dependencies:
  test: ^1.16.5
  conduit_test: ^3.0.0
